"""Draft PR node: synthesizes human reviewer sign-off notes into release Pull Request metadata."""

import os
from typing import List, Optional
from pydantic import BaseModel, Field

from agents.nodes.state import AgentState
from agents.utils.pr_utils import sanitize_branch_name, slugify_title
from llm.ollama_client import llm
from agents.utils.execution_trace import add_execution_event, emit_trace_event
from constants import (
    NODE_DRAFT_PR,
    STATUS_RUNNING,
    STATUS_SUCCESS,
)


class PRDraftOutput(BaseModel):
    branch_name: str = Field(
        description="Clean git branch name, e.g. fix/issue-42-handle-empty-input"
    )
    commit_message: str = Field(
        description="Conventional git commit message, e.g. fix: handle empty input correctly (closes #42)"
    )
    pr_title: str = Field(
        description="Clear, concise pull request title, e.g. fix(core): handle empty input in parser"
    )
    pr_body: str = Field(
        description="Comprehensive markdown PR body including Overview, Root Cause, Changes, Verification, Reviewer Sign-Off, and Closes #X"
    )
    is_draft: bool = Field(
        default=True,
        description="Whether to open the PR on GitHub as a Draft Pull Request"
    )


def generate_fallback_draft(
    issue_number: int,
    issue_title: str,
    changed_files: List[str],
    patch: str,
    human_feedback: Optional[str] = None,
    test_summary: Optional[str] = None,
) -> dict:
    """Deterministic, high-quality PR draft generator when LLM is unavailable."""
    slug = slugify_title(issue_title)
    branch_name = sanitize_branch_name(f"fix/issue-{issue_number}-{slug}", issue_number)

    pr_title = f"fix: {issue_title} (#{issue_number})" if issue_number else f"fix: {issue_title}"
    commit_msg = (
        f"fix: {issue_title} (closes #{issue_number})\n\n"
        f"Automated patch generated by OSA Agent, verified by test suite and reviewed by human operator."
        if issue_number
        else f"fix: {issue_title}"
    )

    files_list = (
        "\n".join(f"- `{f}`" for f in changed_files)
        if changed_files
        else "- Core repository files"
    )

    reviewer_section = (
        f"> **Reviewer Feedback / Approval Notes:**\n> {human_feedback}\n"
        if human_feedback and human_feedback.strip()
        else "> *Approved by human operator after reviewing proposed patch diff.*"
    )

    tests_section = (
        f"Automated test verification passed:\n```\n{test_summary[:500]}\n```"
        if test_summary and test_summary.strip()
        else "Automated test suite passed cleanly."
    )

    pr_body = f"""### 🎯 Overview
Fixes #{issue_number}: {issue_title}

### 🔍 Root Cause & Solution
Automated resolution generated and validated against the repository's test suite to address the issue requirements.

### 🛠️ Changes Implemented
{files_list}

### 🧪 Verification & Tests
{tests_section}

### 👤 Human Reviewer Sign-Off
{reviewer_section}

---
*Draft Pull Request created by OSA Agent for team review and final CI validation.*

Closes #{issue_number}
"""

    return {
        "branch_name": branch_name,
        "commit_message": commit_msg,
        "pr_title": pr_title,
        "pr_body": pr_body.strip(),
        "is_draft": True,
    }


def generate_pr_draft(
    issue_number: int,
    issue_title: str,
    issue_body: str = "",
    changed_files: Optional[List[str]] = None,
    patch: str = "",
    human_feedback: Optional[str] = None,
    test_summary: Optional[str] = None,
    is_draft: bool = True,
) -> dict:
    """Generate rich PR draft incorporating human review notes."""
    changed_files = changed_files or []
    use_llm = os.getenv("OSA_PR_METADATA_LLM", "").strip() == "1"

    if use_llm:
        try:
            prompt = f"""You are a senior release engineer drafting a GitHub Pull Request for an open-source project.

A code patch has been generated, tested, and APPROVED by a human reviewer. Your task is to draft the final release Pull Request.

ISSUE DETAILS:
- Number: #{issue_number}
- Title: {issue_title}
- Description: {issue_body[:600]}

CHANGED FILES:
{", ".join(changed_files) if changed_files else "See patch diff"}

HUMAN REVIEWER NOTES / APPROVAL FEEDBACK:
{human_feedback if human_feedback else "No additional notes; patch approved as-is."}

TEST SUMMARY:
{test_summary if test_summary else "Automated test suite passed cleanly."}

PATCH DIFF PREVIEW:
```diff
{patch[:1500]}
```

REQUIREMENTS:
1. `branch_name`: Clean git branch name (e.g. `fix/issue-{issue_number}-<slug>`).
2. `commit_message`: Conventional commit format with issue reference (e.g. `fix(scope): resolve issue description (closes #{issue_number})`).
3. `pr_title`: Clean, conventional title (e.g. `fix: <title> (#{issue_number})`).
4. `pr_body`: Structured Markdown with:
   - `### 🎯 Overview`: Executive summary.
   - `### 🔍 Root Cause & Solution`: Why it happened and how it was solved.
   - `### 🛠️ Changes Implemented`: Bulleted list of modified files.
   - `### 🧪 Verification`: Test results.
   - `### 👤 Human Reviewer Sign-Off`: Explicitly incorporate human reviewer notes and sign-off.
   - `Closes #{issue_number}`.
5. `is_draft`: Set to True to create as a GitHub Draft PR."""

            structured_llm = llm.with_structured_output(PRDraftOutput)
            result: PRDraftOutput = structured_llm.invoke(prompt)

            return {
                "branch_name": sanitize_branch_name(result.branch_name, issue_number),
                "commit_message": result.commit_message.strip(),
                "pr_title": result.pr_title.strip(),
                "pr_body": result.pr_body.strip(),
                "is_draft": result.is_draft,
            }
        except Exception:
            pass

    return generate_fallback_draft(
        issue_number=issue_number,
        issue_title=issue_title,
        changed_files=changed_files,
        patch=patch,
        human_feedback=human_feedback,
        test_summary=test_summary,
    )


def draft_pr_node(state: AgentState) -> dict:
    """LangGraph node: Executed after Human Review to synthesize the final PR draft."""
    emit_trace_event(
        state,
        node=NODE_DRAFT_PR,
        status=STATUS_RUNNING,
        message="Drafting Pull Request with AI incorporating human review...",
    )

    issue = state.get("issue", {})
    issue_number = issue.get("number", 0)
    issue_title = issue.get("title", "Bug fix")
    issue_body = issue.get("body", "")
    changed_files = state.get("changed_files", [])
    patch = state.get("patch", "")
    human_feedback = state.get("feedback")
    test_result = state.get("test_result", {})
    test_summary = test_result.get("stdout") or test_result.get("stderr") or ""

    metadata = generate_pr_draft(
        issue_number=issue_number,
        issue_title=issue_title,
        issue_body=issue_body,
        changed_files=changed_files,
        patch=patch,
        human_feedback=human_feedback,
        test_summary=test_summary,
        is_draft=True,
    )

    execution_trace = add_execution_event(
        state,
        node=NODE_DRAFT_PR,
        status=STATUS_SUCCESS,
        message=f"Pull Request drafted for #{issue_number} (Draft PR).",
        details={
            "branch_name": metadata["branch_name"],
            "pr_title": metadata["pr_title"],
            "is_draft": metadata["is_draft"],
        },
    )

    return {
        "pr_metadata": metadata,
        "execution_trace": execution_trace,
    }
